### PR TITLE
Fixed unreliable hot reloading

### PR DESCRIPTION
**Pull request by tungv**
1. remove cwd option to yield absolute paths
2. add debounce to avoid multiple restarts happen unexpectedly when more than one file change

### CODE REVIEW

**Comment by leo** [comment]
Looks really good! But how about using a package for the debouncing? The function looks like it could be abstracted away with a package.

**Comment by tungv** [comment]
I initially used lodash, but worried about the size of the package. What do you think about lodash/debounce?

**Comment by leo** [comment]
@tungv I'd rather go with a package that's only doing debouncing, nothing else.

**Comment by tungv** [comment]
Ok Leo, I will update in a few hours. Thanks!

**Comment by tungv** [comment]
hi @leo, I opted to use `debounce` npm package.

their code looks very clean https://unpkg.com/debounce@1.0.2

**Comment by leo** [comment]
Thanks a lot!

**Comment by tungv** [comment]
Great. Thank you for merging this over the weekend. I'm eager to use the new version next week.

**Comment by bakpakin** [comment]
It seems like this merge makes the --ignore option no longer work properly, reverting  #24

**Comment by tungv** [comment]
it's true. `--ignore` with relative paths is broken. How about resolving ignored paths before passing them to chokidar?

**Comment by bakpakin** [comment]
That requires detecting if a pattern is resolvable. Patterns like `**/tmp/**` are valid, but should not be resolved with path.resolve. Essentially, chokidar ignores anymatch patterns, not directories.

**Comment by tungv** [comment]
maybe we should explicitly say that ignore pattern are not relative to cwd.

**Comment by zigomir** [comment]
Interestingly, this doesn't fix hot reloading issue for me. Still same thing as described in https://github.com/zeit/micro-dev/issues/23 :/

**Pull request merged**
